import { AomiMark } from './steward/AomiMark';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Concept, Ecosystem } from './steward/Graphics';
import { fixture, products, usd } from './steward/data';
import './steward/landing.css';
import { ProblemMap } from './steward/ProblemMap';

const demoURL = '/app/nav-oracle';
const steps = ['Exposure review', 'Stress assessment', 'Proposed reallocation', 'Approval package'];

function downloadExample() {
  const blob = new Blob([JSON.stringify({ exampleOnly: true, executable: false, dataset: fixture.id, mandate: { concentrationLimitPct: 30, perActionLimitPct: 15 }, proposal: fixture.plans[0], transactions: [], note: 'Illustrative approval record only. No chain snapshot, calldata, signature, simulation receipt, or live execution is included.' }, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'steward-illustrative-approval-record.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function SectionTitle({ number, eyebrow, title, children }: { number: string; eyebrow: string; title: string; children?: ReactNode }) {
  return <div className="st-section-heading"><div><span className="st-caption">{number} / {eyebrow}</span><h2>{title}</h2></div>{children && <p>{children}</p>}</div>;
}

function Overlay({ mode, close }: { mode: string; close: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [draftReady, setDraftReady] = useState(false);
  useEffect(() => { const el = dialog.current!; const previous = document.activeElement as HTMLElement; el.showModal(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { el.close(); document.body.style.overflow = overflow; previous?.focus(); }; }, []);
  const contact = mode === 'contact';
  return <dialog ref={dialog} className={`st-dialog ${contact ? 'st-dialog-contact' : ''}`} onCancel={e => { e.preventDefault(); close(); }} onClick={e => { if(e.target === e.currentTarget) close(); }} aria-labelledby="st-dialog-title">
    <div className="st-dialog-inner"><button className="st-close" onClick={close} aria-label="Close dialog">×</button><span className="st-caption">{contact ? 'CONTACT / AOMI LABS' : 'EVIDENCE / ILLUSTRATIVE EXAMPLE'}</span><h2 id="st-dialog-title">{contact ? 'Discuss your operating requirements.' : 'The basis behind the example.'}</h2>
    {contact ? <><p>Tell us about your vault structure and the workflow you would like to evaluate.</p><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const body = `Name: ${data.get('name')}\nWork email: ${data.get('email')}\nOrganization: ${data.get('organization')}\nInterest: ${data.get('interest')}\n\n${data.get('requirements') || ''}`; window.location.href = `mailto:contact@aomi.dev?subject=${encodeURIComponent('Steward — institutional inquiry')}&body=${encodeURIComponent(body)}`; setDraftReady(true); }}>
      <label>Name<input autoComplete="name" name="name" required maxLength={120} /></label><label>Work email<input type="email" name="email" autoComplete="email" required maxLength={200} /></label><label>Organization<input name="organization" autoComplete="organization" required maxLength={200} /></label><label>What would you like to evaluate?<select name="interest"><option>All three capabilities</option>{products.map(p => <option key={p.name}>{p.name}</option>)}</select></label><label>Operating requirements <span>(optional)</span><textarea name="requirements" rows={3} maxLength={3000} placeholder="Vault structure, relevant venues, or a workflow to evaluate. Please omit confidential information." /></label>
      <button className="st-button st-button-dark" type="submit">Prepare inquiry email <span>↗</span></button><p className="st-note">Opens your email application addressed to contact@aomi.dev. Nothing is submitted or stored by this page. You review and send the email.</p>{draftReady && <p role="status">Your email application was requested. If it did not open, email <a href="mailto:contact@aomi.dev">contact@aomi.dev</a> directly. No inquiry has been sent by Steward.</p>}
    </form></> : <><p>This interactive walkthrough uses a synthetic $10 million USDC portfolio. It demonstrates the structure of a decision record, not a live valuation or executed simulation.</p><dl className="st-evidence-list">
      <div><dt>Dataset</dt><dd>{fixture.id} · synthetic fixture</dd></div><div><dt>Chain snapshot</dt><dd>None. No block-pinned reads are performed on this page.</dd></div><div><dt>Valuation assumption</dt><dd>USDC = $1; no accrued interest or fees. Nested claims are counted once. This assumption is not a current market quote.</dd></div><div><dt>Stress assumptions</dt><dd>Representative borrower: $6m collateral, $4.5m debt, 86% liquidation loan-to-value. Collateral falls 12% or 15%; usable liquidity falls 45% from $1.4m to $770k.</dd></div><div><dt>Interpretation</dt><dd>A collateral shock does not mechanically reduce the USDC lender’s NAV. Loss requires unrecovered debt; liquidation profitability and realized losses are not modeled here.</dd></div><div><dt>Example mandate</dt><dd>cbBTC-market allocation below 30%; per-action movement no greater than 15% of vault NAV. These are example constraints, not Gauntlet policy.</dd></div><div><dt>Proposed response</dt><dd>$940k moved to reserve: $3.84m − $0.94m = $2.9m, or 29% of unchanged $10m NAV. The example assumes sufficient withdrawal liquidity.</dd></div><div><dt>Execution evidence</dt><dd>None. No fork execution, gas estimate, signature, calldata, transaction, or onchain result is fabricated.</dd></div>
    </dl><button className="st-button" onClick={downloadExample}>Download illustrative record ↓</button><a className="st-text-button" href={demoURL}>Open NAV Oracle ↗</a></>}
    </div>
  </dialog>;
}

function NavPreview() {
  const [position, setPosition] = useState(0);
  const item = fixture.positions[position]!;
  return <div className="st-nav-preview"><div className="st-preview-heading"><span className="st-caption">REFERENCE USDC VAULT</span><span className="st-status">VALUATION OVERVIEW</span></div>
    <div className="st-nav-total"><div><span>Net asset value</span><strong>$10,000,000<span>.00</span></strong></div><span className="st-caption">4 POSITIONS<br />1 VALUATION BASIS</span></div>
    <div className="st-allocation-bar" aria-label="Portfolio: 38.4% cbBTC market, 31.6% WETH market, 20% nested vault, 10% reserve">{fixture.positions.map((p, i) => <button key={p.label} style={{ width: `${p.share}%` }} className={`st-bar-${i}`} onClick={() => setPosition(i)} aria-label={`Inspect ${p.label}`} />)}</div>
    <div className="st-position-list">{fixture.positions.map((p, i) => <button key={p.label} aria-expanded={position === i} onClick={() => setPosition(i)}><i className={`st-bar-${i}`} /><span>{p.label}</span><b>{usd(p.amount)}</b><small>{p.share.toFixed(1)}%</small><span aria-hidden="true">{position === i ? '−' : '+'}</span></button>)}</div>
    <div className="st-position-detail" aria-live="polite"><span className="st-caption">LOOK-THROUGH / {item.label}</span><p>{item.detail}</p>{position === 2 && <div className="st-nested"><span>↳ USDC lending <b>$1,200,000</b></span><span>↳ USDC reserve <b>$800,000</b></span></div>}<div className="st-source-tag">Valuation basis <b>USDC / $1.00 assumed</b></div></div>
  </div>;
}

function StressPreview() {
  const [scenario, setScenario] = useState(1); const s = fixture.scenarios[scenario]!;
  return <div><div className="st-preview-heading"><span className="st-caption">REPRESENTATIVE BORROWER</span><span className="st-status">SCENARIO ASSESSMENT</span></div><div className="st-segment st-scenarios">{fixture.scenarios.map((s, i) => <button key={s.label} aria-pressed={scenario===i} onClick={() => setScenario(i)}>{s.label}</button>)}</div>
    <div className="st-stress-top"><div><span>Loan-to-value after shock</span><strong>{s.ltv.toFixed(2)}<small>%</small></strong></div><span className={s.breach ? 'st-warning' : 'st-status'}>{s.verdict}</span></div>
    <svg className="st-stress-chart" viewBox="0 0 580 140" role="img" aria-label={`Loan-to-value ${s.ltv}% against an 86% liquidation threshold`}><rect x="20" y="42" width="530" height="35" rx="2" fill="var(--st-paper)" /><rect x="20" y="42" width={s.ltv*5.3} height="35" fill={s.breach ? 'var(--st-peach)' : 'var(--st-blue)'} /><path d="M475.8 26V102" stroke="var(--st-ink)" strokeDasharray="4 4" /><text x="476" y="18" textAnchor="end">86% liquidation threshold</text><text x="20" y="121">0%</text><text x="550" y="121" textAnchor="end">100%</text></svg>
    <div className="st-stat-grid"><div><span>Collateral value</span><b>{usd(s.collateral)}</b><small>Starting value $6,000,000</small></div><div><span>USDC debt</span><b>$4,500,000</b><small>Held constant in this example</small></div><div><span>Usable liquidity</span><b>{usd(s.capacity)}</b><small>{s.liquidity ? '−45% from baseline' : 'Baseline assumption'}</small></div><div><span>Collateral shock</span><b>{s.shock ? `−${s.shock}%` : 'None'}</b><small>Price sensitivity, not a forecast</small></div></div><p className="st-note">Threshold sensitivity only. No fork execution or liquidation recovery is represented; vault losses are not inferred from the price shock.</p>
  </div>;
}

function BuilderPreview() {
  const [plan, setPlan] = useState(0); const p = fixture.plans[plan]!;
  return <div><div className="st-preview-heading"><span className="st-caption">MANDATE / CONCENTRATION &lt; 30%</span><span className="st-status">PROPOSAL REVIEW</span></div><h3 className="st-ask">“Reduce our cbBTC-market exposure below 30%.”</h3><div className="st-plan-list">{fixture.plans.map((p, i) => <button key={p.name} aria-pressed={plan===i} onClick={() => setPlan(i)}><span className="st-plan-radio">{plan===i ? '●' : '○'}</span><span><b>{p.name}</b><small>{p.status}</small></span><strong>{p.residual}%</strong></button>)}</div>
    <div className="st-plan-detail" aria-live="polite"><div><span>Proposed movement</span><b>{usd(p.move)}</b></div><div><span>Residual concentration</span><b>38.4% → {p.residual}%</b></div><p>{p.note}</p><span className={p.allowed ? 'st-status' : 'st-warning'}>{p.allowed ? 'ILLUSTRATIVE CHECKS PASSED' : 'CANDIDATE REJECTED'}</span></div><button className="st-text-button" onClick={downloadExample}>Inspect illustrative approval record ↓</button>
  </div>;
}

export function Landing() {
  const [tab, setTab] = useState(0); const [step, setStep] = useState(0); const [overlay, setOverlay] = useState<string | null>(null); const [menu, setMenu] = useState(false);
  const p = products[tab]!;
  useEffect(() => { const title = document.title; document.title = 'Intelligence and control for vault operations.'; return () => { document.title = title; }; }, []);
  function openProduct(i: number) { setTab(i); document.getElementById('st-products')?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); }
  return <div className="steward" id="st-top">
    <a className="st-skip" href="#st-products">Skip to products</a>
    <header className="st-header"><a className="st-brand" href="#st-top"><span className="st-brand-icon"><AomiMark size={24} /></span>steward<span className="st-brand-by">BY AOMI LABS</span></a><button className="st-menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>☰</button><nav className={menu ? 'st-nav st-nav-open' : 'st-nav'} aria-label="Main navigation">{[['Products','st-products'],['Ecosystem','st-ecosystem'],['Approach','st-approach'],['Aomi Labs','st-labs']].map(([name, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{name}</a>)}</nav><a className="st-button st-header-contact" href="/app/nav-oracle">Open App <span>↗</span></a></header>
    <main className="st-main">
      <section className="st-hero"><div className="st-hero-copy"><span className="st-caption"><i className="st-live-dot" /> INSTITUTIONAL VAULT OPERATIONS</span><h1>Intelligence and control for <em>vault operations.</em></h1><p>Portfolio valuation, scenario analysis, and transaction preparation within manager-defined mandates.</p><p className="st-hero-assurance">Investment decisions, custody, and signing authority remain with your organization.</p><div className="st-hero-actions"><button className="st-button st-button-dark" onClick={() => setOverlay('contact')}>Request a demonstration <span>↗</span></button><a className="st-text-button" href="#st-products">Explore capabilities <span>↓</span></a></div></div>
      <div className="st-hero-visual"><div className="st-visual-title"><span className="st-caption">THE OPERATING LAYER</span><span className="st-caption">01 — 03</span></div><div className="st-hero-diagram"><Concept kind={0} hero /><span className="st-orbit-label">TRACEABLE INPUTS. REVIEWABLE OUTPUTS.</span></div><div className="st-hero-stages">{products.map((p,i) => <button className={`st-stage st-${p.color}`} key={p.name} onClick={() => openProduct(i)}><span>0{i+1}</span><b>{p.name}</b><small>{['Valuation report','Scenario assessment','Approval package'][i]}</small><i>↗</i></button>)}</div><div className="st-visual-footer"><span>Mandate-defined preparation</span><span>In-house authority ↗</span></div></div></section>
      <div className="st-principles"><span>Built for curators, asset managers & treasury teams</span><span>Valuation transparency</span><span>Scenario evidence</span><span>Manager-controlled signing</span></div>
      <ProblemMap />
      <section className="st-section" id="st-products"><SectionTitle number="02" eyebrow="CAPABILITIES" title="Three disciplines. One operating layer.">Start with the workflow you need. Connect the outputs as your operating requirements evolve.</SectionTitle><div className="st-product-tabs" role="tablist" aria-label="Steward products">{products.map((p, i) => <button key={p.name} id={`st-tab-${i}`} role="tab" aria-selected={tab===i} aria-controls="st-product-panel" tabIndex={tab===i?0:-1} onClick={() => setTab(i)} onKeyDown={e => { let next = i; if(e.key==='ArrowRight') next=(i+1)%3; else if(e.key==='ArrowLeft') next=(i+2)%3; else if(e.key==='Home') next=0; else if(e.key==='End') next=2; else return; e.preventDefault(); setTab(next); document.getElementById(`st-tab-${next}`)?.focus(); }} className={`st-${p.color}`}><span>0{i+1}</span><b>{p.name}</b><span>↗</span></button>)}</div>
      <div className={`st-product-panel st-${p.color}`} role="tabpanel" id="st-product-panel" aria-labelledby={`st-tab-${tab}`}><div className="st-product-copy"><span className="st-caption">{p.category}</span><h3>{p.headline}</h3><p>{p.description}</p><ul>{p.features.map(f => <li key={f}>{f}</li>)}</ul><Concept kind={tab} /><div className="st-deliverable"><span className="st-caption">DELIVERABLE</span><b>{p.output}</b>{tab === 0 && <a className="st-text-button" href="/app/nav-oracle">Open NAV Oracle ↗</a>}</div></div><div className="st-product-output"><div className="st-fixture-label"><i /> Illustrative example · fixture data</div>{tab===0?<NavPreview/>:tab===1?<StressPreview/>:<BuilderPreview/>}<div className="st-output-footer"><span>No live reads, signing, or execution</span><button onClick={() => setOverlay('evidence')}>View evidence ↗</button></div></div></div></section>
      <section className="st-section" id="st-ecosystem"><SectionTitle number="03" eyebrow="ECOSYSTEM" title="A connected view of vault operations.">Curators, venues, and execution controls have distinct roles. Steward supports the work between them.</SectionTitle><Ecosystem /></section>
      <section className="st-section" id="st-approach"><SectionTitle number="04" eyebrow="AUTHORITY & EVIDENCE" title="Operational support. Retained authority.">Preparation and decision-making have a clear boundary. Your organization defines the mandate and authorizes the action.</SectionTitle><div className="st-boundary"><div className="st-boundary-head"><h3>Steward boundary</h3><h3>In-house control</h3></div>{[['Valuation reports & source references','Valuation policies & approved sources'],['Scenario results & constraint checks','Risk assumptions & investment mandates'],['Transaction proposals & simulation evidence','Approval, signing & submission']].map(([a,b],i)=><div className="st-boundary-row" key={a}><span><small>0{i+1}</small>{a}</span><span>{b}<i>↗</i></span></div>)}<div className="st-evidence-strip"><span>EVIDENCE ATTACHED TO THE RELEVANT OUTPUT</span><b>Snapshot</b><b>Sources</b><b>Assumptions</b><b>Validation</b><button onClick={() => setOverlay('evidence')}>Inspect example ↗</button></div></div></section>
      <section className="st-section" id="st-example"><SectionTitle number="05" eyebrow="WORKED EXAMPLE" title="One mandate. A complete decision record.">Follow a concentration review through assessment, proposed response, and manager approval.</SectionTitle><div className="st-walkthrough"><div className="st-example-meta"><span>REFERENCE USDC VAULT / $10M NAV</span><span>Illustrative example · not a live vault</span></div><div className="st-step-tabs" role="group" aria-label="Walkthrough steps">{steps.map((s,i)=><button key={s} aria-pressed={step===i} onClick={()=>setStep(i)}><small>0{i+1}</small><b>{s}</b><span>→</span></button>)}</div><div className="st-step-panel" aria-live="polite"><div><span className="st-caption">{['OBSERVATION','SENSITIVITY','PROPOSED RESPONSE','MANAGER REVIEW'][step]}</span><h3>{['Concentration exceeds the example mandate.','Collateral stress narrows the safety margin.','A targeted move restores the allocation limit.','A proposal is not an authorization.'][step]}</h3><p>{['The cbBTC-collateralized market accounts for $3.84m, or 38.4% of vault NAV. The example concentration limit is 30%.','A representative borrower moves from 75% to 85.23% LTV after a 12% collateral decline—near the 86% liquidation threshold. This does not, by itself, establish vault loss.','Reallocate $940k from the cbBTC market to unallocated USDC. Residual allocation is $2.9m, or 29% of NAV. Movement is 9.4% of NAV, below the 15% example bound.','The manager reviews the rationale, assumptions, and validation requirements. A production package requires fresh-state checks and exact calldata before approval and signing.'][step]}</p><button className="st-text-button" onClick={() => setOverlay('evidence')}>Review assumptions & evidence ↗</button></div><div className="st-step-art">{step===0?<><span className="st-caption">MARKET CONCENTRATION</span><strong>38.4<small>%</small></strong><div className="st-threshold-line"><i style={{width:'76.8%'}}/><b style={{left:'60%'}} /></div><span>Example limit: 30%</span></>:step===1?<><span className="st-caption">BORROWER LOAN-TO-VALUE</span><strong>85.23<small>%</small></strong><span>Liquidation threshold: 86%</span><small>Collateral −12% · debt held constant</small></>:step===2?<><span className="st-caption">RESIDUAL CONCENTRATION</span><strong>29<small>%</small></strong><span>$940,000 → unallocated USDC</span><small>NAV unchanged under fixture assumptions</small></>:<><span className="st-caption">APPROVAL RECORD</span><span className="st-package-symbol">↳</span><b>Unsigned. Unsubmitted.</b><button className="st-button" onClick={downloadExample}>Download example ↓</button></>}</div></div></div></section>
      <section className="st-section st-labs" id="st-labs"><div className="st-labs-mark"><AomiMark size={90}/><span>aomi labs</span><small>EXECUTION INFRASTRUCTURE</small></div><div><span className="st-caption">06 / BUILT BY AOMI LABS</span><h2>Steward is built<br/>by Aomi Labs.</h2><p>Aomi Labs develops execution infrastructure for onchain finance: transaction construction, simulation, integration with signing controls, and result verification.</p><p>Steward applies that foundation to the operating requirements of vault managers.</p><div className="st-labs-links"><a href="https://aomi.dev" target="_blank" rel="noreferrer">Explore Aomi Labs ↗</a><a href="https://aomi.dev/contact" target="_blank" rel="noreferrer">Speak with the team ↗</a></div></div></section>
      <section className="st-invitation"><span className="st-caption">START A CONVERSATION</span><h2>Discuss your<br/><em>operating requirements.</em></h2><div><p>Evaluate Steward against your vault structure, valuation policies, risk mandates, and approval process.</p><button className="st-button st-button-dark" onClick={()=>setOverlay('contact')}>Contact the team <span>↗</span></button></div></section>
    </main>
    <footer className="st-footer"><a className="st-brand" href="#st-top">steward<span className="st-brand-by">BY AOMI LABS</span></a><span>© {new Date().getFullYear()} Aomi Labs</span><div><a href={demoURL}>Open App ↗</a><a href="https://aomi.dev/contact">Contact</a><a href="https://aomi.dev/privacy">Privacy</a></div></footer>
    {overlay && <Overlay mode={overlay} close={()=>setOverlay(null)}/>}
  </div>;
}
